### ISSUE TITLE
native-or-bluebird is deprecated. please switch to any-promise

### ISSUE THREAD

**Issue by jonathanong** [afc163/exeq#11]
https://github.com/kevinbeaty/any-promise

this implementation supports more promise implementations and allows the end-user to configure the promise implementation.

**Comment by afc163** [comment]
Pull request is welcome.

**Comment by IonicaBizau** [comment]
@afc163 This issue is obsolete as of https://github.com/afc163/exeq/commit/41f770f2e70f16675bc684e380d7e05c9ff78bba, right?

<sub>PS: Sorry for spamming you, but one of the organizations I was being member converted me into external collaborator, so it spammed all my followers...</sub> :sob:

**Comment by afc163** [comment]
Yes, it can be closed.
