### ISSUE TITLE
不能保留子进程的颜色显示? 

### ISSUE THREAD

**Issue by sorrycc** [afc163/exeq#5]
![image](https://cloud.githubusercontent.com/assets/35128/5851305/3119f16e-a240-11e4-9099-0e40f8afffb4.png)

**Comment by sorrycc** [comment]
google 了下，貌似不好解决。

**Comment by afc163** [comment]
是不好解决。

**Comment by afc163** [comment]
有颜色了就拿不到输出。

或者可以强制某命令输出 ansi ，比如 `mocha --color`

**Comment by sorrycc** [comment]
https://github.com/lepture/colorful/blob/master/lib/ansi.js#L15
子进程这里是 false，而且没找到接口可以强制指定。考虑要不要换个库。

**Comment by afc163** [comment]
先给他 PR 好了。换库的话可以用 https://www.npmjs.com/package/chalk

**Comment by sorrycc** [comment]
找到接口了，`require('colorful').isatty = true;`
